### ISSUE TITLE
Actualizar header de secciones

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/mxabierto.org#167]
![screen_shot_2016-06-27_at_10_31_12](https://cloud.githubusercontent.com/assets/2633527/16385558/ef1a3e46-3c52-11e6-8a69-14c51fce7e47.png)

**Comment by chuckcfs** [comment]
@carlosmaya si ubican que ya hay una sección `Herramientas` en el sitio verdad?

<img width="1126" alt="screen shot 2016-06-27 at 12 48 21" src="https://cloud.githubusercontent.com/assets/1383865/16389865/9da6bb62-3c65-11e6-8b46-337b7faca98b.png">

**Comment by carlosmaya** [comment]
@chuckcfs buen punto, entonces la actualización quedaría así

![screen_shot_2016-06-27_at_13_39_06](https://cloud.githubusercontent.com/assets/2633527/16392097/c17da4d8-3c6f-11e6-96f4-c089c07960f1.png)
